name: Daily Sentiment Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"   # every day @ 04:00 UTC (adjust as you like)

jobs:
  build-report:
    runs-on: ubuntu-latest

    env:       # pass all secrets/vars into the R session
      SUPABASE_URL:           ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE:  ${{ secrets.SUPABASE_SERVICE_ROLE }}
      MJ_API_KEY:             ${{ secrets.MJ_API_KEY }}
      MJ_API_SECRET:          ${{ secrets.MJ_API_SECRET }}
      MAIL_FROM:              ${{ vars.MAIL_FROM }}
      MAIL_TO:                ${{ vars.MAIL_TO }}
      REPORT_DATE:            ${{ vars.REPORT_DATE || '' }}   # blank → today
      CI: true
      R_KEEP_PKG_SOURCE: no

    steps:
      # 1  Checkout code
      - uses: actions/checkout@v4

      # 2  Set up R + pandoc
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2

      # 3  Install headless Chrome for pagedown
      - name: Install headless Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          chrome-version: stable

      # 4  System libs for text & graphics packages
      - name: Install linux libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libfontconfig1 libharfbuzz-dev libfribidi-dev \
            libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      # 5  Run the end‑to‑end script
      - name: Render & send daily sentiment report
        run: Rscript run_daily_sentiment.R

      # 6  Upload artefacts (optional, for debugging)
      - name: Upload artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-sentiment-artifacts
          path: |
            daily_sentiment_report.html
            daily_sentiment_report.pdf
          if-no-files-found: warn
